# Generated by Django 2.2.4 on 2019-09-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_twit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
